name: Go CI/CD Pipeline  

on:  
  push:  
    branches:  
      - main  
  pull_request:  
    branches:  
      - main  

jobs:  
  build:  
    runs-on: ${{ matrix.os }}  
    strategy:  
      matrix:  
        os: [ubuntu-latest, windows-latest, macos-latest]  

    steps:  
      - name: Checkout Code  
        uses: actions/checkout@v3  

      - name: Set up Go  
        uses: actions/setup-go@v3  
        with:  
          go-version: '1.23.3'

      - name: Build  
        run: go build -o linecounter main.go  

      - name: Run Tests  
        run: go test  

  deploy:  
    runs-on: ubuntu-latest  
    needs: build  
    steps:  
      - name: Checkout Code  
        uses: actions/checkout@v3  

      - name: Deploy to Remote Server  
        env:  
          HOST: ${{ secrets.HOST }}  
          USER: ${{ secrets.USER }}  
          KEY: ${{ secrets.KEY }}  
        run: |  
          echo "$KEY" > private_key.pem  
          chmod 600 private_key.pem  
          scp -i private_key.pem -o StrictHostKeyChecking=no linecounter $USER@$HOST:/path/to/deploy/
